#!/usr/bin/env bash
# Bring the template's tooling in this repo up to a newer oryx-overlay release.
#
# "Use this template" copies the files without the template's history, so git
# can't merge template fixes. Instead, for every template-owned path listed in
# .oryx-overlay-manifest, this does a 3-way merge per file:
#   base   = the file at the release in .oryx-overlay-version (what you started from)
#   ours   = your working copy
#   theirs = the file at the new release
# Files you never touched are replaced, your edits are kept where they don't
# overlap the template's, and overlapping edits get conflict markers. New template
# files are added; files the template deleted are removed only if you hadn't
# changed them. layout/, custom/, oryx.conf and docs/ are never written, nor any
# path listed in .oryx-overlay-keep (yours to own, one path or folder per line).
#
# The result is left uncommitted for you to review: git diff, then
#   git commit -am "template: upgrade to <ref>"
#
# Usage: scripts/self-update.sh            (or: make self-update [TO=<ref>])
# Environment:
#   TO                     tag, branch or commit to upgrade to (default: newest v* tag)
#   FROM                   release your copy is at, if .oryx-overlay-version is missing or wrong
#   ORYX_OVERLAY_UPSTREAM  template repository (default https://github.com/ggfevans/oryx-overlay.git)
#
# Exit codes: 0 updated or already current, 1 error, 3 merge conflicts left to resolve.

# shellcheck source=scripts/lib.sh
source "$(dirname "$0")/lib.sh"

UPSTREAM="${ORYX_OVERLAY_UPSTREAM:-https://github.com/ggfevans/oryx-overlay.git}"
VERSION_FILE=".oryx-overlay-version"
MANIFEST=".oryx-overlay-manifest"
KEEP_FILE=".oryx-overlay-keep"
NS="refs/oryx-overlay"
ABANDON="To abandon the upgrade instead: git reset --hard"

# Everything runs inside main, and the last line calls it and exits in one go:
# this script is itself template-owned and may be rewritten while it runs, and
# bash reads a script as it goes.
main() {
  local arg
  for arg in "$@"; do
    case "$arg" in
      -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
      *) die "unknown option: $arg (set TO=<ref> to pick a release)" ;;
    esac
  done

  cd "$ROOT" || exit 1
  [[ "$(git rev-parse --show-toplevel 2>/dev/null)" == "$(pwd -P)" ]] \
    || die "$ROOT is not the top of a git repository"
  # docs/ is regenerated by every build and never written here, so it may be dirty.
  if [[ -n "$(git status --porcelain -- . ':(exclude)docs')" ]]; then
    git status --short -- . ':(exclude)docs' >&2
    die "working tree has uncommitted changes; commit or stash them first, so the upgrade is easy to review and undo"
  fi

  # One self-update at a time: they share the fetched refs and the working tree.
  acquire_lock "$(git rev-parse --absolute-git-dir)/oryx-overlay-update.lock" self-update
  TMP="$(mktemp -d "${TMPDIR:-/tmp}/oryx-overlay-update.XXXXXX")"
  trap cleanup EXIT

  log "Fetching $UPSTREAM"
  git fetch --quiet --no-tags "$UPSTREAM" "+refs/heads/*:$NS/heads/*" "+refs/tags/*:$NS/tags/*" \
    || die "could not fetch $UPSTREAM (set ORYX_OVERLAY_UPSTREAM to use another copy of the template)"

  local from_name to_name from to
  from_name="${FROM:-}"
  if [[ -z "$from_name" ]] && [[ -f "$VERSION_FILE" ]]; then
    from_name="$(head -n 1 "$VERSION_FILE" | tr -d '[:space:]')"
  fi
  [[ -n "$from_name" ]] \
    || die "$VERSION_FILE is missing, so the template version this repo started from is unknown. Rerun with FROM=<tag or commit of the template you copied>, e.g. FROM=v0.1.0 make self-update"
  from="$(resolve "$from_name")" \
    || die "$from_name (from ${FROM:+FROM}${FROM:-$VERSION_FILE}) is not a tag, branch or commit in $UPSTREAM. Rerun with FROM=<tag or commit of the template you copied>."

  to_name="${TO:-}"
  if [[ -z "$to_name" ]]; then
    to_name="$(git for-each-ref --sort=-v:refname --count=1 --format='%(refname:strip=3)' "$NS/tags/v[0-9]*")"
    [[ -n "$to_name" ]] || die "$UPSTREAM has no release tags yet. Pick a ref: TO=main make self-update"
  fi
  to="$(resolve "$to_name")" || die "$to_name is not a tag, branch or commit in $UPSTREAM"

  # Record a tag by name; anything else (a branch moves) by its commit.
  local record="$to"
  git show-ref --verify --quiet "$NS/tags/$to_name" && record="$to_name"

  if [[ "$from" == "$to" ]]; then
    ok "Already at $to_name; nothing to update."
    write_version "$record"
    return 0
  fi

  git cat-file -e "$to:$MANIFEST" 2>/dev/null || die "$to_name has no $MANIFEST; it predates self-update"
  log "Updating template files: $from_name -> $to_name"

  # Manifest entries from both releases, so paths the template dropped are seen too.
  local entries=() e
  while IFS= read -r e; do
    entries+=("$e")
  done < <({ git show "$to:$MANIFEST"; git show "$from:$MANIFEST" 2>/dev/null || true; } \
             | sed -e 's/#.*//' -e 's/[[:space:]]*$//' -e 's|/*$||' -e '/^$/d' | sort -u)
  (( ${#entries[@]} )) || die "$MANIFEST in $to_name lists no paths"

  { git --literal-pathspecs ls-tree -r --full-tree --name-only "$from" -- "${entries[@]}"
    git --literal-pathspecs ls-tree -r --full-tree --name-only "$to" -- "${entries[@]}"
  } | sort -u >"$TMP/paths"

  N_UPDATED=0 N_ADDED=0 N_REMOVED=0 N_MERGED=0
  CONFLICTS=() NOTES=()
  local path
  while IFS= read -r path; do
    if protected "$path"; then
      NOTES+=("skipped $path: yours, never written by self-update")
      continue
    fi
    if kept "$path"; then
      NOTES+=("skipped $path: listed in $KEEP_FILE")
      continue
    fi
    update_path "$path" "$from" "$to" "$from_name" "$to_name"
  done <"$TMP/paths"

  write_version "$record"

  ok "$N_UPDATED updated, $N_MERGED merged with your edits, $N_ADDED added, $N_REMOVED removed"
  local n
  for n in ${NOTES[@]+"${NOTES[@]}"}; do warn "$n"; done
  shadow_hints "$to"
  changelog "$from" "$to"

  if (( ${#CONFLICTS[@]} )); then
    printf '\n%sConflicts%s: your edits and the template both changed these files. Resolve the <<<<<<< markers, then commit:\n' "$C_R" "$C_0" >&2
    for n in "${CONFLICTS[@]}"; do printf '  %s\n' "$n" >&2; done
    printf '\n%s\n' "$ABANDON" >&2
    return 3
  fi
  cat >&2 <<EOF

Review the changes (git status, git diff), then commit them:
  git commit -am "template: upgrade to $to_name"
$ABANDON
EOF
}

# shellcheck disable=SC2329  # run by the EXIT trap
cleanup() {
  local ref
  [[ -n "${TMP:-}" ]] && rm -rf "$TMP"
  # The fetched template refs were only needed for this run.
  git for-each-ref --format='%(refname)' "$NS/" 2>/dev/null | while IFS= read -r ref; do
    git update-ref -d "$ref" 2>/dev/null || true
  done
  release_lock
}

# True if no existing part of the path above the file is a symlink, so writing
# or deleting it can't reach outside this repository.
parents_are_real() {
  local dir
  dir="$(dirname "$1")"
  while [[ "$dir" != "." ]] && [[ "$dir" != "/" ]]; do
    [[ -L "$dir" ]] && return 1
    dir="$(dirname "$dir")"
  done
  return 0
}

# Commit for a name in the template: tag, then branch, then a commit id.
resolve() {
  local name="$1" c
  for c in "$NS/tags/$name" "$NS/heads/$name"; do
    if git show-ref --verify --quiet "$c"; then
      git rev-parse --verify --quiet "$c^{commit}"
      return
    fi
  done
  [[ "$name" =~ ^[0-9a-f]{7,40}$ ]] || return 1
  git rev-parse --verify --quiet "$name^{commit}"
}

# Never written, whatever a manifest says.
protected() {
  case "$1" in
    layout|layout/*|custom|custom/*|docs|docs/*|oryx.conf|"$VERSION_FILE"|"$KEEP_FILE") return 0 ;;
  esac
  return 1
}

# Listed in .oryx-overlay-keep (a path or a folder).
kept() {
  local p
  [[ -f "$KEEP_FILE" ]] || return 1
  while IFS= read -r p; do
    p="${p%%#*}"
    p="$(printf '%s' "$p" | sed -e 's/[[:space:]]*$//' -e 's|/*$||')"
    [[ -n "$p" ]] || continue
    [[ "$1" == "$p" || "$1" == "$p"/* ]] && return 0
  done <"$KEEP_FILE"
  return 1
}

# "<mode> <sha>" of a path in a commit, empty if absent or not a plain file.
entry() {
  local line
  line="$(git --literal-pathspecs ls-tree --full-tree "$1" -- "$2")"
  case "$line" in
    100644\ blob\ *|100755\ blob\ *) line="${line%%$'\t'*}"; printf '%s %s' "${line%% *}" "${line##* }" ;;
  esac
}

# Write a blob to a path with the template's file mode.
put() {
  local path="$1" mode="$2" sha="$3"
  mkdir -p "$(dirname "$path")"
  git cat-file blob "$sha" >"$TMP/blob"
  # Replace, not truncate in place: the file may be a script that is running.
  mv -f "$TMP/blob" "$path"
  set_mode "$path" "$mode"
}

set_mode() {
  if [[ "$2" == 100755 ]]; then chmod +x "$1"; else chmod -x "$1"; fi
}

update_path() {
  local path="$1" from="$2" to="$3" from_name="$4" to_name="$5"
  local base theirs bmode bsha tmode tsha ours=""
  base="$(entry "$from" "$path")"
  theirs="$(entry "$to" "$path")"
  bmode="${base%% *}" bsha="${base##* }" tmode="${theirs%% *}" tsha="${theirs##* }"
  if ! parents_are_real "$path"; then
    NOTES+=("skipped $path: a folder above it is a symlink here, so writing it could reach outside this repo")
    return
  fi
  if [[ -L "$path" ]] || { [[ -e "$path" ]] && [[ ! -f "$path" ]]; }; then
    NOTES+=("skipped $path: not a regular file here")
    return
  fi
  [[ -f "$path" ]] && ours="$(git hash-object -- "$path")"

  if [[ -z "$theirs" ]]; then
    # The template deleted it (or it's no longer a plain file there).
    [[ -n "$base" ]] && [[ -n "$ours" ]] || return 0
    if [[ "$ours" == "$bsha" ]]; then
      rm -f "$path"
      rmdir -p "$(dirname "$path")" 2>/dev/null || true
      N_REMOVED=$((N_REMOVED + 1))
    else
      NOTES+=("kept $path: the template removed it in $to_name, but you had changed it")
    fi
    return 0
  fi

  if [[ -z "$ours" ]]; then
    if [[ -z "$base" ]]; then
      put "$path" "$tmode" "$tsha"
      git add --intent-to-add -- "$path"  # so git diff and git commit -a include it
      N_ADDED=$((N_ADDED + 1))
    elif [[ "$bsha" != "$tsha" ]]; then
      NOTES+=("kept your deletion of $path; the template changed it in $to_name (git show $to:$path)")
    fi
    return 0
  fi

  if [[ "$ours" == "$tsha" ]]; then
    set_mode "$path" "$tmode"
    return 0
  fi
  if [[ -n "$base" ]] && [[ "$ours" == "$bsha" ]]; then
    put "$path" "$tmode" "$tsha"
    N_UPDATED=$((N_UPDATED + 1))
    return 0
  fi
  if [[ -n "$base" ]] && [[ "$bsha" == "$tsha" ]]; then
    [[ "$bmode" == "$tmode" ]] || set_mode "$path" "$tmode"
    return 0  # only you changed it
  fi

  # Both sides changed it (or both added it): 3-way merge into the working copy.
  if [[ -n "$base" ]]; then git cat-file blob "$bsha" >"$TMP/base"; else : >"$TMP/base"; fi
  git cat-file blob "$tsha" >"$TMP/theirs"
  cp "$path" "$TMP/ours"
  local rc=0
  git merge-file -L "yours" -L "template $from_name" -L "template $to_name" \
    "$TMP/ours" "$TMP/base" "$TMP/theirs" 2>"$TMP/merge.err" || rc=$?
  if (( rc < 0 || rc > 127 )); then
    CONFLICTS+=("$path (could not merge: $(head -n 1 "$TMP/merge.err"); kept yours, the template's is at git show $to:$path)")
    return 0
  fi
  mv -f "$TMP/ours" "$path"
  [[ -n "$base" && "$bmode" == "$tmode" ]] || set_mode "$path" "$tmode"
  if (( rc > 0 )); then
    CONFLICTS+=("$path")
  else
    N_MERGED=$((N_MERGED + 1))
  fi
}

write_version() {
  [[ "$(cat "$VERSION_FILE" 2>/dev/null)" == "$1" ]] && return 0
  printf '%s\n' "$1" >"$VERSION_FILE"
  git ls-files --error-unmatch -- "$VERSION_FILE" >/dev/null 2>&1 \
    || git add --intent-to-add -- "$VERSION_FILE"
}

# Your custom/modules/ copy of a module wins over the template's modules/ (an older
# template kept its modules in custom/), so template fixes to it won't reach you.
shadow_hints() {
  local to="$1" mod
  [[ -d custom/modules ]] || return 0
  for mod in custom/modules/*/*/; do
    mod="${mod%/}"
    [[ -f "$mod/qmk_module.json" ]] || continue
    if git cat-file -e "$to:${mod#custom/}/qmk_module.json" 2>/dev/null; then
      warn "$mod replaces the template's ${mod#custom/}. If you never changed it, delete it to get the template's fixes: git rm -r $mod"
    fi
  done
}

# The new release's CHANGELOG.md sections that the old release didn't have.
changelog() {
  local from="$1" to="$2"
  git show "$to:CHANGELOG.md" >"$TMP/new.md" 2>/dev/null || return 0
  git show "$from:CHANGELOG.md" 2>/dev/null | grep '^## ' | grep -v '^## Unreleased' >"$TMP/old-headings" || true
  printf '\n%sWhat changed%s (CHANGELOG.md):\n\n' "$C_B" "$C_0" >&2
  awk -v seen="$TMP/old-headings" '
    BEGIN { while ((getline line < seen) > 0) old[line] = 1 }
    /^## / { if ($0 in old) exit; printing = 1 }
    printing { print }
  ' "$TMP/new.md" >&2
}

main "$@"; exit $?
