#!/usr/bin/env bash
# Pull the latest layout from Oryx and merge it into the current branch.
#
# How it works:
#   1. The `oryx` branch only ever receives untouched Oryx exports in layout/.
#   2. Each sync commits the newest export to `oryx`.
#   3. `oryx` is merged into your branch, so git replays only what changed in
#      Oryx on top of your own edits (the same idea as poulainpi/oryx-with-custom-qmk).
#
# Usage: scripts/sync.sh [--push] [--ci]
#   --push  push to origin (the oryx branch is pushed even if the merge conflicts)
#   --ci    non-interactive: abort the merge on conflict instead of leaving it open
#
# Exit codes: 0 ok (changed or not), 3 merge conflict.

# shellcheck source=scripts/lib.sh
source "$(dirname "$0")/lib.sh"

PUSH=0 CI_MODE=0
for arg in "$@"; do
  case "$arg" in
    --push) PUSH=1 ;;
    --ci) CI_MODE=1 ;;
    -h|--help) sed -n '2,17p' "$0"; exit 0 ;;
    *) die "unknown option: $arg" ;;
  esac
done

load_config
cd "$ROOT" || exit 1
git rev-parse --git-dir >/dev/null 2>&1 || die "not a git repository"

CURRENT="$(git rev-parse --abbrev-ref HEAD)"
[[ "$CURRENT" != "oryx" ]] || die "you're on the oryx branch; check out your main branch first"
[[ "$CURRENT" != "HEAD" ]] || die "detached HEAD; check out a branch first"
# docs/ is regenerated by every build and never touched by the oryx branch, so it can stay dirty.
if [[ -n "$(git status --porcelain --untracked-files=no -- . ':(exclude)docs')" ]]; then
  die "working tree has uncommitted changes; commit or stash them first"
fi

WT="$CACHE_DIR/oryx-worktree"
cleanup() { git worktree remove --force "$WT" >/dev/null 2>&1 || true; }
trap cleanup EXIT
cleanup
git worktree prune

HAS_ORIGIN=0
git remote get-url origin >/dev/null 2>&1 && HAS_ORIGIN=1

REMOTE_ORYX=0
if [[ $HAS_ORIGIN == 1 ]] && git ls-remote --exit-code --heads origin oryx >/dev/null 2>&1; then
  git fetch --quiet origin oryx:refs/remotes/origin/oryx
  REMOTE_ORYX=1
fi

if git show-ref --verify --quiet refs/heads/oryx; then
  git worktree add --quiet "$WT" oryx
  if [[ $REMOTE_ORYX == 1 ]] && ! git -C "$WT" merge --quiet --ff-only origin/oryx 2>/dev/null; then
    # Local and remote both have exports (e.g. a local sync and a CI sync). Both
    # only touch layout/, and the fetch below overwrites layout/ anyway.
    git -C "$WT" merge --quiet --no-edit -X theirs -m "oryx: merge exports from origin" origin/oryx \
      || die "could not reconcile the local and remote oryx branches"
  fi
elif [[ $REMOTE_ORYX == 1 ]]; then
  git worktree add --quiet -b oryx "$WT" origin/oryx
else
  # First sync. Branch from the last commit that holds an untouched Oryx export
  # (the last one to change layout/.oryx.json), not from HEAD: then any edits you
  # already made in layout/ are merged with the new export instead of overwritten.
  BASE="$(git log -1 --format=%H -- layout/.oryx.json)"
  [[ -n "$BASE" ]] || BASE="$(git rev-parse HEAD)"
  log "Creating the oryx branch from $(git log -1 --format='%h "%s"' "$BASE") (first sync)"
  git worktree add --quiet -b oryx "$WT" "$BASE"
fi

log "Fetching layout '$ORYX_LAYOUT_ID' ($ORYX_GEOMETRY) from Oryx"
FETCH_OUT="$("$PY" "$ROOT/scripts/oryx_fetch.py" --layout-id "$ORYX_LAYOUT_ID" --geometry "$ORYX_GEOMETRY" --out "$WT/layout")"
get() { printf '%s\n' "$FETCH_OUT" | sed -n "s/^$1=//p"; }
REVISION="$(get revision)"
VERSION="$(get qmk_version)"
NOTE="$(get change_note)"
[[ -n "$NOTE" ]] || NOTE="Oryx revision $REVISION"

RC=0
(
  cd "$WT"
  git add -A layout
  if git diff --cached --quiet; then
    exit 10
  fi
  # Key-level summary of what changed, for the commit body.
  SUMMARY=""
  if git cat-file -e HEAD:layout/keymap.c 2>/dev/null; then
    SUMMARY="$("$PY" "$ROOT/scripts/oryx_layout.py" --style "$LEGEND_STYLE" diff HEAD:layout/keymap.c layout/keymap.c \
      --meta layout/.oryx.json 2>/dev/null | head -n 60 || true)"
  fi
  git commit --quiet -m "oryx: $NOTE" -m "Oryx revision $REVISION, firmware v$VERSION." ${SUMMARY:+-m "$SUMMARY"}
) || RC=$?

case $RC in
  0) ok "New Oryx revision $REVISION committed to the oryx branch: $NOTE" ;;
  10) ok "Oryx layout unchanged (revision $REVISION)" ;;
  *) die "committing to the oryx branch failed" ;;
esac

if [[ $PUSH == 1 ]]; then
  [[ $HAS_ORIGIN == 1 ]] || die "--push given but there is no 'origin' remote"
  git push --quiet origin oryx
fi

if git merge-base --is-ancestor oryx HEAD; then
  ok "$CURRENT already contains the latest Oryx export"
else
  log "Merging oryx into $CURRENT"
  if ! git merge --quiet --no-edit -Xignore-all-space -m "Merge Oryx changes: $NOTE" oryx; then
    CONFLICTS="$(git diff --name-only --diff-filter=U)"
    printf '\n%sMerge conflict%s between Oryx changes and your edits in:\n%s\n\n' "$C_R" "$C_0" "$CONFLICTS" >&2
    if [[ $CI_MODE == 1 ]]; then
      git merge --abort
      printf 'Resolve locally: run "make sync", fix the files above, then commit.\n' >&2
    else
      cat >&2 <<'EOF'
Resolve it: Oryx's side wins for anything Oryx generates (the keymaps array,
ledmap, macros, tap dances); your side wins for code you added. Keep your
additions marked `// [custom]` so they're easy to spot. Then:
  git add <files> && git commit      # finish the merge
  make build                         # prove it still compiles
Or ask Claude Code: /oryx-sync resolve
EOF
    fi
    exit 3
  fi
  ok "Merged"
fi

if [[ $PUSH == 1 ]]; then
  git push --quiet origin "HEAD:$CURRENT"
  ok "Pushed oryx and $CURRENT"
fi
